stages:
  - build
  - trigger


build_job:
    stage: build
    before_script:
      - echo $BUILD_TAGS
    script:
      - time docker save dockerhub.io/main/mrs:$BUILD_TAGS dockerhub.io/main/zodiac:$BUILD_TAGS dockerhub.io/main/log-enrichment:$BUILD_TAGS > mainxrs.tar
      - time pbzip2 -9 -p15 -m5000 mainxrs.tar
      - sed -i "s/mainxrs (1.0.3)/mainxrs ($BUILD_TAGS)/" debian/changelog
      - time dpkg-buildpackage -j8 -Zbzip2 || true
      - mv ../*.deb /home/share/debs/
    only:
      - triggers
      - pipelines


# trigger_job:
#     stage: trigger
#     trigger:
#         project: main/main-build
#         strategy: depend
#         branch: master
#     only:
#       - triggers
#       - pipelines
